### ISSUE TITLE
Please provides cryptographic signature

### ISSUE THREAD

**Issue by kenhys** [takaswie/libhinawa#42]
I want to support cryptographic signature verification in next package update.

ref. https://wiki.debian.org/debian/watch#Cryptographic_signature_verification

Here is the summary:

Upstream: 
* upload a signed file (such as libhinawa-0.7.0.tar.gz.asc)

```
gpg2 --local-user XXX --armor --detach-sign  libhinawa-0.7.0.tar.gz
```

Packager:
* add debian/upstream/signing-key.asc
* update debian/watch to support pgpsigurlmangle option

**Comment by takaswie** [comment]
Good idea. Go ahead.
https://github.com/takaswie/libhinawa/releases/tag/0.7.0

**Comment by takaswie** [comment]
I push a remote branch for your idea.
https://github.com/takaswie/libhinawa/commit/e0390837d707257b7437c912b468500f7fc749d6

Please implement the idea based on this branch, then PR.

**Comment by kenhys** [comment]
I've send PR.
https://github.com/takaswie/libhinawa/pull/44

There is one concern. I did simple test case to verify, but uscan claims to it.

```
% LANG=C uscan 
uscan: Newest version of libhinawa on remote site is 0.7.0, local version is 0.6.0
uscan:    => Newer package available from
      https://github.com/takaswie/libhinawa/archive/0.7.0.tar.gz
gpgv: Signature made Mon May  2 08:15:27 2016 JST using RSA key ID D66FD341
gpgv: BAD signature from "Takashi Sakamoto <o-takashi@sakamocchi.jp>"
uscan warn: OpenPGP signature did not verify.
```

**Comment by takaswie** [comment]
```
$ uscan --verbose
uscan info: uscan (version 2.16.2ubuntu3) See uscan(1) for help
uscan info: Scan watch files in .
uscan info: Check debian/watch and debian/changelog in .
uscan info: package="libhinawa" version="0.7.0-2" (as seen in debian/changelog)
uscan info: package="libhinawa" version="0.7.0" (no epoch/revision)
uscan info: ./debian/changelog sets package="libhinawa" version="0.7.0"
uscan info: Process ./debian/watch (package=libhinawa version=0.7.0)
uscan info: Found upstream signing keyring: debian/upstream/signing-key.asc
uscan info: opts: filenamemangle=s/.+\/v?(\d\S*)\.tar\.gz/libhinawa-$1\.tar\.gz/,pgpsigurlmangle=s/(.+)archive\/v?(\d\S*)\.tar\.gz/$1\/releases\/download\/$2\/libhinawa-$2\.tar\.gz\.asc/
uscan info: line: https://github.com/takaswie/libhinawa/tags .*/v?(\d\S*)\.tar\.gz
uscan info: Parsing filenamemangle=s/.+\/v?(\d\S*)\.tar\.gz/libhinawa-$1\.tar\.gz/
uscan info: Parsing pgpsigurlmangle=s/(.+)archive\/v?(\d\S*)\.tar\.gz/$1\/releases\/download\/$2\/libhinawa-$2\.tar\.gz\.asc/
uscan info: line: https://github.com/takaswie/libhinawa/tags .*/v?(\d\S*)\.tar\.gz
uscan info: Last orig.tar.* tarball version (from debian/changelog): 0.7.0
uscan info: Last orig.tar.* tarball version (dversionmangled): 0.7.0
uscan info: Requesting URL:
   https://github.com/takaswie/libhinawa/tags
uscan info: Matching pattern:
   (?:(?:https://github.com)?\/takaswie\/libhinawa\/tags)?.*/v?(\d\S*)\.tar\.gz
uscan info: Found the following matching hrefs on the web page (newest first):
   /takaswie/libhinawa/archive/0.7.0.tar.gz (0.7.0) index=0.7.0-1 
   /takaswie/libhinawa/archive/0.6.0.tar.gz (0.6.0) index=0.6.0-1 
   /takaswie/libhinawa/archive/0.5.0.tar.gz (0.5.0) index=0.5.0-1 
   /takaswie/libhinawa/archive/0.4.0.tar.gz (0.4.0) index=0.4.0-1 
   /takaswie/libhinawa/archive/0.3.0.tar.gz (0.3.0) index=0.3.0-1 
uscan info: Matching target for downloadurlmangle: https://github.com/takaswie/libhinawa/archive/0.7.0.tar.gz
uscan info: Upstream URL (downloadurlmangled):
   https://github.com/takaswie/libhinawa/archive/0.7.0.tar.gz
uscan info: Newest upstream tarball version selected for download (uversionmangled): 0.7.0
uscan info: Matching target for filenamemangle: /takaswie/libhinawa/archive/0.7.0.tar.gz
uscan info: Download filename (filenamemangled): libhinawa-0.7.0.tar.gz
uscan: Newest version of libhinawa on remote site is 0.7.0, local version is 0.7.0
uscan info:    => Package is up to date for from
      https://github.com/takaswie/libhinawa/archive/0.7.0.tar.gz
uscan info: Not downloading upstream package: libhinawa-0.7.0.tar.gz
uscan info: Downloading OpenPGP signature from
   https://github.com/takaswie/libhinawa//releases/download/0.7.0/libhinawa-0.7.0.tar.gz.asc (pgpsigurlmangled)
   as libhinawa-0.7.0.tar.gz.pgp
uscan info: Requesting URL:
   https://github.com/takaswie/libhinawa//releases/download/0.7.0/libhinawa-0.7.0.tar.gz.asc
uscan warn: FAIL Checking OpenPGP signature (no upstream tarball downloaded).
uscan info: Scan finished
```

I guess that 'pgpsigurlmangle' is invalid in 'debian/watch'. The uscan utility attempted to download it from the URL to release archive and use it as my public key.

**Comment by kenhys** [comment]
Thanks.
I overlooked what actually uscan do. I've fixed #44.

**Comment by takaswie** [comment]
In this take, I can generate deb package. On the other hand, still see the warning.

```
$ uscan -v
uscan info: uscan (version 2.16.2ubuntu3) See uscan(1) for help
uscan info: Scan watch files in .
uscan info: Check debian/watch and debian/changelog in .
uscan info: package="libhinawa" version="0.7.0-2" (as seen in debian/changelog)
uscan info: package="libhinawa" version="0.7.0" (no epoch/revision)
uscan info: ./debian/changelog sets package="libhinawa" version="0.7.0"
uscan info: Process ./debian/watch (package=libhinawa version=0.7.0)
uscan info: Found upstream signing keyring: debian/upstream/signing-key.asc
uscan info: opts: pgpsigurlmangle=s/$/.asc/
uscan info: line: https://github.com/takaswie/libhinawa/releases .*/libhinawa-(\d\S*)\.tar\.gz
uscan info: Parsing pgpsigurlmangle=s/$/.asc/
uscan info: line: https://github.com/takaswie/libhinawa/releases .*/libhinawa-(\d\S*)\.tar\.gz
uscan info: Last orig.tar.* tarball version (from debian/changelog): 0.7.0
uscan info: Last orig.tar.* tarball version (dversionmangled): 0.7.0
uscan info: Requesting URL:
   https://github.com/takaswie/libhinawa/releases
uscan info: Matching pattern:
   (?:(?:https://github.com)?\/takaswie\/libhinawa\/releases)?.*/libhinawa-(\d\S*)\.tar\.gz
uscan info: Found the following matching hrefs on the web page (newest first):
   /takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz (0.7.0) index=0.7.0-1 
uscan info: Matching target for downloadurlmangle: https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz
uscan info: Upstream URL (downloadurlmangled):
   https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz
uscan info: Newest upstream tarball version selected for download (uversionmangled): 0.7.0
uscan info: Download filename (filenamemangled): libhinawa-0.7.0.tar.gz
uscan: Newest version of libhinawa on remote site is 0.7.0, local version is 0.7.0
uscan info:    => Package is up to date for from
      https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz
uscan info: Not downloading upstream package: libhinawa-0.7.0.tar.gz
uscan info: Downloading OpenPGP signature from
   https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz.asc (pgpsigurlmangled)
   as libhinawa-0.7.0.tar.gz.pgp
uscan info: Requesting URL:
   https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz.asc
uscan warn: FAIL Checking OpenPGP signature (no upstream tarball downloaded).
uscan info: Scan finished
```

When executing 'uscan -vv', I see uscan downloads this URL, instead of released archive or signature:
https://github.com/takaswie/libhinawa/releases

Is this an expected behaviour?

**Comment by takaswie** [comment]
In this week, I have little time for userspace because I have heavy work for Linux 4.7. It's OK to receive more comments and RP, however my reaction may be dellayed till next week (opening merge window for Linux 4.7), sorry.

**Comment by kenhys** [comment]
It is not an expected behaviour, thus it is a bug about uscan.

```
% uscan -v
uscan info: uscan (version 2.16.4) See uscan(1) for help
uscan info: Scan watch files in .
uscan info: Check debian/watch and debian/changelog in .
uscan info: package="libhinawa" version="0.7.0-2" (as seen in debian/changelog)
uscan info: package="libhinawa" version="0.7.0" (no epoch/revision)
uscan info: ./debian/changelog sets package="libhinawa" version="0.7.0"
uscan info: Process ./debian/watch (package=libhinawa version=0.7.0)
uscan info: Found upstream signing keyring: debian/upstream/signing-key.asc
uscan info: opts: pgpsigurlmangle=s/$/.asc/
uscan info: line: https://github.com/takaswie/libhinawa/releases .*/libhinawa-(\d\S*)\.tar\.gz
uscan info: Parsing pgpsigurlmangle=s/$/.asc/
uscan info: line: https://github.com/takaswie/libhinawa/releases .*/libhinawa-(\d\S*)\.tar\.gz
uscan info: Last orig.tar.* tarball version (from debian/changelog): 0.7.0
uscan info: Last orig.tar.* tarball version (dversionmangled): 0.7.0
uscan info: Requesting URL:
   https://github.com/takaswie/libhinawa/releases
uscan info: Matching pattern:
   (?:(?:https://github.com)?\/takaswie\/libhinawa\/releases)?.*/libhinawa-(\d\S*)\.tar\.gz
uscan info: Found the following matching hrefs on the web page (newest first):
   /takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz (0.7.0) index=0.7.0-1 
uscan info: Matching target for downloadurlmangle: https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz
uscan info: Upstream URL (downloadurlmangled):
   https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz
uscan info: Newest upstream tarball version selected for download (uversionmangled): 0.7.0
uscan info: Download filename (filenamemangled): libhinawa-0.7.0.tar.gz
uscan: Newest version of libhinawa on remote site is 0.7.0, local version is 0.7.0
uscan info:    => Package is up to date for from
      https://github.com/takaswie/libhinawa/releases/download/0.7.0/libhinawa-0.7.0.tar.gz
uscan info: Scan finished
```

and this bug is fixed at devscripts 2.16.4.
Here is the changelog. You can see details here (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822233)

```
devscripts (2.16.4) unstable; urgency=medium

  * mk-build-deps:
    + Only remove the deb after install if --remove was specified.
  * uscan:
    + Return early from process_watchline if no download or sig verification
      is taking place.  (Closes: #822233)

 -- James McCoy <jamessan@debian.org>  Sat, 23 Apr 2016 21:33:42 -0400
```

**Comment by takaswie** [comment]
```
and this bug is fixed at devscripts 2.16.4.
Here is the changelog. You can see details here (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822233)
```

Thanks. I confirmed that the update has never come to Ubuntu.

**Comment by takaswie** [comment]
Merged.
